### ISSUE TITLE
Nonexhaustive pattern in `TBQueue`

### ISSUE THREAD

**Issue by bgamari** [haskell/stm#49]
The GHC build, which builds with `-Werror`, fails after bumping to 2.5.0.1 due to:
```

libraries/stm/Control/Concurrent/STM/TBQueue.hs:133:15: error: [-Wincomplete-uni-patterns, -Werror=incomplete-uni-patterns]
    Pattern match(es) are non-exhaustive
    In a pattern binding: Patterns of type ‘[a]’ not matched: []
    |
133 |           let (z:zs) = reverse ys -- NB. lazy: we want the transaction to be
    |               ^^^^^^^^^^^^^^^^^^^

libraries/stm/Control/Concurrent/STM/TBQueue.hs:173:15: error: [-Wincomplete-uni-patterns, -Werror=incomplete-uni-patterns]
    Pattern match(es) are non-exhaustive
    In a pattern binding: Patterns of type ‘[a]’ not matched: []
    |
173 |           let (z:zs) = reverse ys -- NB. lazy: we want the transaction to be
    |               ^^^^^^^^^^^^^^^^^^^
```
